import React from 'react';
import './TC.css';

const TermsAndConditions = () => {
  return (
    <div className="tc-container">
      <div className="rentique-privacy-policy">
    <h1 className="tc-title">Terms & Conditions</h1>
    <p className="tc-paragraph">
        This document is an electronic record under Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes under applicable Indian laws. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>
      <p className="tc-paragraph">
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms for access or usage of www.rentique.com website.
      </p>
      <p className="tc-paragraph">
        The domain name www.rentique.com (hereinafter referred to as ‘Website’) is owned by [Your Company Name], a company incorporated under the Companies Act, 1956 with its registered office at [Your Address] (hereinafter referred to as "Rentique").
      </p>
      <p className="tc-paragraph">
        Your use of the Website, services, Mobile Application, and tools are governed by the following terms and conditions (‘Terms of Use’) as applicable. If You transact on the Website, You shall be subject to the policies that are applicable to the Website for such transactions. By mere use of the Website, you shall be contracting with Rentique and these terms and conditions including the policies constitute your binding obligations with Rentique.
      </p>

      <h2 className="tc-section-heading">Your Account and Registration Obligations</h2>
      <p className="tc-paragraph">
        If You use the Website, You shall be responsible for maintaining the confidentiality of Your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of Your membership on the Website and refuse to provide You with access to the Website.
      </p>

      <h2 className="tc-section-heading">Privacy</h2>
      <p className="tc-paragraph">
        Rentique collects, stores, processes and uses Your information in accordance with our Privacy Policy. By using the Website and/ or by providing your information, you consent to the collection and use of the information you disclose on the Website by Rentique in accordance with Rentique’s Privacy Policy.
      </p>

      <h2 className="tc-section-heading">Use of the Website</h2>
      <p className="tc-paragraph">
        You shall not host, display, upload, modify, publish, transmit, update or share any information which:
      </p>
      <ul className="tc-list">
        <li className="tc-list-item">Belongs to another person and to which You does not have any right to;</li>
        <li className="tc-list-item">Is grossly harmful, harassing, blasphemous, defamatory, obscene, violent, pornographic, pedophilic, offensive, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, illegal, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to ‘indecent representation of women’ within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986; or soliciting personal information from anyone;</li>
        <li className="tc-list-item">Is misleading in any way;</li>
        <li className="tc-list-item">Involves the transmission of ‘junk mail’, ‘chain letters’, or unsolicited mass mailing or ‘spamming’;</li>
        <li className="tc-list-item">Infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];</li>
        <li className="tc-list-item">Contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);</li>
        <li className="tc-list-item">Tries to gain unauthorized access or exceeds the scope of authorized access to the Website;</li>
        <li className="tc-list-item">Impersonates another person;</li>
        <li className="tc-list-item">Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any Trojan horses, worms, time bombs, cancel bots, Easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;</li>
      </ul>
      <p className="tc-paragraph">
        You shall not use any ‘deep-link’, ‘page-scrape’, ‘robot’, ‘spider’ or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any server, computer, network, or to any of the services offered on or through the Website, by hacking, password ‘mining’ or any other illegitimate means. We reserve Our right to bar any such activity.
        You shall not probe, scan or test the vulnerability of the Website or any network neither connected to the Website nor breach the security or authentication measures on the Website or any network connected to the Website. 
        You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the terms Rentique, Website, or otherwise engage in any conduct or action that might tarnish the image or reputation, of Rentique or sellers on platform or otherwise tarnish or dilute any Rentique's trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or our systems or networks, or any systems or networks connected to Rentique.
        You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person's use of the Website.
        You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Website or any service offered on or through the Website. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.
      </p>

      <h2 className="tc-section-heading">Disclaimer of Warranties and Liability</h2>
      <p className="tc-paragraph">
        Rentique and its suppliers, affiliates and service providers provide the Website and services on "as is" basis and without any warranty or condition, express, implied or statutory and specifically disclaim any implied warranties of title, merchantability, fitness for a particular purpose and non-infringement. You expressly agree that your use of the Website is at your risk.
        Rentique does not warrant that this site; information, Content, materials, product (including software) or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from Us are free of viruses or other harmful components or error free or uninterrupted.
      </p>

    <h2 className="tc-section-heading">Payment</h2>
    <p className="tc-paragraph">
        While availing any of the payment method(s) available on the Website, we will not be responsible or assume any liability whatsoever in respect to any loss or damage arising directly or indirectly to You due to:
      </p>
      <ul className="tc-list">
        <li className="tc-list-item">Lack of authorization for any transaction(s), or</li>
        <li className="tc-list-item">Exceeding the present limit mutually agreed by You and between ‘Bank(s)’, or</li>
        <li className="tc-list-item">Any payment issues arising out of the transaction, or</li>
        <li className="tc-list-item">Decline of transaction for any other reason(s).</li>
    </ul>
    <p className="tc-paragraph">
        All payments made against the purchases/related services on Website by You shall be compulsorily in Indian Rupees acceptable in the Republic of India. The Website will not facilitate transactions in any other form of currency with respect to the purchases made on Website. Rentique uses a third-party service provider to facilitate and collect payments (‘Payment Facility’) and Rentique is not liable or responsible for any issue between You and such third-party service provider.
      </p>

    <h2 className="tc-section-heading">General</h2>
    <p className="tc-paragraph">
        None of the provisions of the Terms of Use shall be deemed to constitute a partnership or agency between You and Rentique and You shall have no authority to bind Rentique in any manner whatsoever nor shall we have any authority to bind you in any manner whatsoever. All the services provided by us shall be as independent contractor and on principal to principal basis.
        If any clause of the Terms of Use shall be deemed invalid, void or for any reason unenforceable, such clause shall be deemed severable and shall not affect the validity and enforceability of the remaining clauses of the Terms of Use.
        This Terms of Use sets forth the entire understanding and agreement between You and Rentique with respect to the subject matter hereof.
        In Rentique’s sole discretion, Rentique may transfer its rights and obligations under this Agreement, assign this Agreement or novate this Agreement without your prior express consent.
      </p>

    <h2 className="tc-section-heading">Limitation of Liability</h2>
    <p className="tc-paragraph">
        In no event shall Rentique be liable for any special, incidental, indirect or consequential damages of any kind in connection with these terms of use.
    </p>
    </div>
    </div>
);
};

export default TermsAndConditions;